sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- cd "Algorithms and Data Structures - Reference"
- pdflatex -interaction=nonstopmode -halt-on-error AD.tex
- pdflatex -interaction=nonstopmode -halt-on-error AD.tex
- pdflatex -interaction=nonstopmode -halt-on-error AD.tex
- pdflatex -interaction=nonstopmode -halt-on-error AD.tex
- pdflatex -interaction=nonstopmode -halt-on-error AD.tex
- cd ..
- cd "Design and Evaluation of User Interfaces- Reference"
- pdflatex -interaction=nonstopmode -halt-on-error DEB.tex
- pdflatex -interaction=nonstopmode -halt-on-error DEB.tex
- pdflatex -interaction=nonstopmode -halt-on-error DEB.tex
- pdflatex -interaction=nonstopmode -halt-on-error DEB.tex
- pdflatex -interaction=nonstopmode -halt-on-error DEB.tex
- cd ..
after_success:
- curl --ftp-create-dirs -T '{Algorithms and Data Structures - Reference/AD.pdf,Design and Evaluation of User Interfaces- Reference/DEB.pdf}' -u $FTP_USERNAME:$FTP_PASSWORD ftp://files.simwir.dk/notes/$TRAVIS_BRANCH/