sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build "Algorithms and Data Structures - Reference"/AD.tex
deploy:
  "curl --ftp-create-dirs -T "{_build/AD.pdf}" -u $FTP-USERNAME:$FTP-PASSWORD ftp://files.simwir.dk/notes/"
