sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- cd "Algorithms and Data Structures - Reference"
- pdflatex -interaction=nonstopmode -halt-on-error AD.tex
- cd ..
after_success:
- curl --ftp-create-dirs -T '{"Algorithms and Data Structures - Reference"/AD.pdf}' -u $FTP_USERNAME:$FTP_PASSWORD ftp://files.simwir.dk/notes/